#!/usr/bin/env bash
# Generates .env.cloud from the linked Supabase project via the CLI.
# Usage: bash scripts/setup-env-cloud.sh [--project-ref <ref>]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
OUT="$ROOT_DIR/.env.cloud"

# ── resolve project ref ──────────────────────────────────────────────────────
PROJECT_REF=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-ref) PROJECT_REF="$2"; shift 2 ;;
    *) shift ;;
  esac
done

if [[ -z "$PROJECT_REF" ]]; then
  # Try to read from supabase/.temp/project-ref (set by `supabase link`)
  TEMP_REF="$ROOT_DIR/supabase/.temp/project-ref"
  if [[ -f "$TEMP_REF" ]]; then
    PROJECT_REF="$(cat "$TEMP_REF")"
  fi
fi

if [[ -z "$PROJECT_REF" ]]; then
  echo "ERROR: No linked Supabase project found."
  echo "Run: supabase link --project-ref <ref>"
  echo "Or:  bash scripts/setup-env-cloud.sh --project-ref <ref>"
  exit 1
fi

echo "Using project ref: $PROJECT_REF"

# ── fetch anon key via CLI ───────────────────────────────────────────────────
echo "Fetching API keys..."
ANON_KEY="$(supabase projects api-keys --project-ref "$PROJECT_REF" \
  | grep '^ *anon' | awk -F'|' '{gsub(/ /, "", $2); print $2}')"

if [[ -z "$ANON_KEY" ]]; then
  echo "ERROR: Could not read anon key. Run: supabase projects api-keys --project-ref $PROJECT_REF"
  exit 1
fi

# ── build URLs ───────────────────────────────────────────────────────────────
SUPABASE_URL="https://${PROJECT_REF}.supabase.co"
DB_HOST="db.${PROJECT_REF}.supabase.co"

# ── prompt for DB password ───────────────────────────────────────────────────
echo ""
echo "Your Supabase DB password is required for the backend connection."
echo "Find it: Supabase dashboard → Project Settings → Database → Connection string"
echo ""
read -rsp "Enter DB password (input hidden): " DB_PASSWORD
echo ""

if [[ -z "$DB_PASSWORD" ]]; then
  echo "ERROR: DB password cannot be empty."
  exit 1
fi

DB_URL="postgresql://postgres:${DB_PASSWORD}@${DB_HOST}:5432/postgres"

# ── write .env.cloud (backend) ───────────────────────────────────────────────
cat > "$OUT" <<EOF
# Generated by scripts/setup-env-cloud.sh — DO NOT COMMIT
# Run locally against remote Supabase with: npm run dev:cloud

# Backend — Supabase connection
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_DB_URL=${DB_URL}

# GitHub OAuth app — create at https://github.com/settings/developers
# Homepage URL: http://localhost:5174
# Callback URL: http://localhost:3003/auth/github/callback
# GITHUB_CLIENT_ID=
# GITHUB_CLIENT_SECRET=
# GITHUB_CALLBACK_URL=http://localhost:3003/auth/github/callback
EOF

echo "Written: $OUT"

# ── write packages/frontend/.env.cloud (Vite browser vars) ──────────────────
FRONTEND_OUT="$ROOT_DIR/packages/frontend/.env.cloud"
cat > "$FRONTEND_OUT" <<EOF
# Generated by scripts/setup-env-cloud.sh — DO NOT COMMIT
VITE_SUPABASE_URL=${SUPABASE_URL}
VITE_SUPABASE_ANON_KEY=${ANON_KEY}
EOF

echo "Written: $FRONTEND_OUT"
echo ""
echo "Start with remote Supabase:  npm run dev:cloud"
